### ISSUE TITLE
Funktionen ToDo

### ISSUE THREAD

**Issue by martinschilliger** [martinschilliger/Rettung-St.Gallen-Aemtliplan#10]
- [x] PDF-Anhänge ermöglichen => Wo speichern?
- [x] Erledigte Ämtli nach unten schieben
- [x] Abschluss: Parse.com aus Development-Modus

**Comment by martinschilliger** [comment]
https://github.com/martinschilliger/Rettung-St.Gallen-Aemtliplan/commit/273a43429fea7373c05cc9ddbab23afedb13ab64

**Comment by martinschilliger** [comment]
Ämtli 3460 integrieren in eigenes Issue ausgelagert
